# Generated by Django 4.2.16 on 2024-11-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_creditcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
