# Generated by Django 4.2.16 on 2024-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_listing_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
